services:

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    links:
      - "web:web"
    volumes:
      - "web-static:/usr/src/app/static"

  web:
    build: ./web
    expose:
      - 8000
    links:
      - "redis:redis"
      # - "postgres:postgres"
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: bash -c "
      celery -A quizbowl worker -n worker1@%h -Q default -c 1 --loglevel=ERROR &
      celery -A quizbowl worker -n worker2@%h -Q default -c 1 --loglevel=ERROR &
      celery -A quizbowl worker -n worker3@%h -Q default -c 1 --loglevel=ERROR &
      celery -A quizbowl worker -n worker4@%h -Q default -c 1 --loglevel=ERROR &
      celery -A quizbowl worker -n worker5@%h -Q default -c 1 --loglevel=ERROR &
      python manage.py collectstatic --noinput --clear &&
      daphne -b 0.0.0.0 -p 8000 quizbowl.asgi:application"
    depends_on:
      - redis
      # - postgres

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - "redisdata:/data"

  # celery:
  #   build:
  #     context: .
  #     dockerfile: ./web/Dockerfile.celery
  #   container_name: celery
  #   command: celery -A quizbowl worker -q
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - web
  #     - redis

  # Commented out because using an AWS RDS Database instead of a container
  # postgres:
  #   image: postgres:latest
  #   expose:
  #     - 5432
  #   env_file: .env
  #   environment: 
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASS}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/
  
volumes:
  web-static:
  redisdata:
  # pgdata: