version: '3'

services:

  nginx:
    build: ./nginx
    volumes:
      - "web-static:/usr/src/app/static"
    ports:
      - "80:80"
    links:
      - "web:web"

  web:
    build: ./web
    expose:
      - 8000
    links:
      - "redis:redis"
      - "postgres:postgres"
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: bash -c "
      python manage.py collectstatic --noinput --clear &&
      daphne -b 0.0.0.0 -p 8000 quizbowl.asgi:application"

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - "redisdata:/data"

  postgres:
    image: postgres:latest
    expose:
      - 5432
    env_file: .env
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  web-static:
  redisdata:
  pgdata: