version: '3'

services:

  nginx:
    build: ./nginx
    volumes:
      - web-static:/usr/src/app/static
      - certdata:/etc/letsencrypt/live
      - cert-webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web

  certbot:
    image: certbot/certbot
    volumes:
      - certdata:/etc/letsencrypt/live
      - cert-webroot:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --register-unsafely-without-email --agree-tos -d kuiperbowl.com -d www.kuiperbowl.com

  web:
    build: ./web
    expose:
      - 8000
    links:
      - redis:redis
      - postgres:postgres
    volumes:
      - web-static:/usr/src/app/static
    env_file: .env
    command: bash -c "
      cd /usr/src/app &&
      python manage.py collectstatic --noinput --clear &&
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 quizbowl.asgi:channel_layer"

  worker:
    build: ./web
    env_file: .env
    command: bash -c "cd /usr/src/app && python manage.py runworker"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  web-static:
  redisdata:
  pgdata:
  certdata:
  cert-webroot: